# Generated by Django 4.1.2 on 2022-12-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=23)),
                ('hardware_api_key', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('value_type', models.IntegerField(choices=[(0, 'Weight'), (1, 'Temperature'), (2, 'Humidity')])),
                ('date', models.PositiveBigIntegerField()),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hive')),
            ],
        ),
    ]
