# Generated by Django 4.1.7 on 2023-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hive_hardware_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
